sudo: false

language: python

python:
- '2.7'
- '3.3'
- pypy

install:
- pip install -U pip setuptools
- pip install flake8 hacking

before_script:
- flake8

script:
- python setup.py install
- gshell --help
